### ISSUE TITLE
DevOps intake checklist for louis-backend

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/louis-backend#18]
## Checklist

* [x] **Project Initialization and Documentation**
   * [x] Internal AI Project intake and criteria for internal AI products.
   * [x] Product functionality explained in the Wiki.
   * [x] [GitHub project created](https://github.com/orgs/ai-cfia/projects) for managing the product.
   * [x] [Configure repository to our own internal standards](https://github.com/ai-cfia/devops/blob/main/github-repository-creation-guide.md).
   * [x] Architecture documented with a diagram.

* [ ] **Developer Documentation**
   * [ ] Setup and installation guide.
   * [ ] Tests documentation.

* [ ] **Testing**
   * [ ] Automated unit test suite
   * [ ] Unit test suite implemented with a minimum of X% code coverage.
   * [ ]  Manual test plan established.

* [ ] **Continuous Integration and Deployment**
   * [ ] Continuous lint, test, build, and deployment pipeline established.
   * [ ] Code conforms to linting standards.
   * [ ] Code builds into a container without errors.
   * [ ] Code deployable to the cloud and accessible via a publicly available URL.

* [ ] **Monitoring and Reporting**
   * [ ] Monitoring and reporting mechanisms in place.
   * [ ] Reporting of daily active users available.
